# https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ConfigurationOptions

server.modules = ( "mod_access", "mod_accesslog" )
server.username = "lighttpd"
server.groupname = "lighttpd"
server.document-root = "/var/www/localhost/htdocs"

index-file.names = ( "index.html" )
static-file.exclude-extensions = ( ".cgi" )
# server.errorlog (defaults to STDERR)
accesslog.filename = "/var/log/lighttpd/access.log"

# https://wiki.archlinux.org/title/Gitweb

server.modules += ( "mod_alias", "mod_cgi", "mod_redirect", "mod_setenv" )
url.redirect += ( "^/gitweb$" => "/gitweb/" )
alias.url += ( "/gitweb/" => "/usr/share/gitweb/" )
$HTTP["url"] =~ "^/gitweb/" {
    setenv.add-environment = (
        "GITWEB_CONFIG" => "/etc/gitweb.conf",
        "NASVCS_GIT_PROJECTROOT" => env.NASVCS_GIT_PROJECTROOT,
        "PATH" => env.PATH,
        "SERVER_NAME" => env.HOSTNAME
    )
    cgi.assign = ( ".cgi" => "" )
    server.indexfiles = ( "gitweb.cgi" )
}

# https://github.com/viewvc/viewvc/blob/master/INSTALL
# TODO: fix missing links for application mimetypes (json php xsl yaml yml) https://mimetype.io

server.modules += ( "mod_alias", "mod_cgi", "mod_redirect", "mod_setenv" )
url.redirect += ( "^/viewvc$" => "/viewvc/" )
alias.url += ( "/viewvc/" => "/opt/nasvcs/viewvc/bin/cgi/" )
$HTTP["url"] =~ "^/viewvc/" {
    cgi.assign = ( ".cgi" => "" )
    server.indexfiles = ( "viewvc.cgi" )
}
