# nasvcs compose example
services:
  nasvcs:
    # image: ghcr.io/jabenninghoff/nasvcs:latest
    image: nasvcs:dev
    build:
      context: .
      args:
        - NASVCS_VERSION=0.0.1-dev
    restart: unless-stopped
    hostname: nasvcs.test
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./sshkeys:/opt/nasvcs/etc/ssh
      - ./vcs:/opt/nasvcs/vcs
    environment:
      - NASVCS_GIT_PROJECTROOT=/opt/nasvcs/vcs/git
